version: 2

sources:
  - name: infass
    description: Inflation Assistant tables
    database: "{{ target.database }}"
    schema: "{{ target.schema }}"
    tables:
      - name: merc
        description: Merc historical product prices

        config:
          freshness:
            warn_after: { count: 7, period: day }
            error_after: { count: 8, period: day }
          loaded_at_field: date

        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - date
                - dedup_id
                - name
                - size
                - category
                - subcategory
                - original_price
                - discount_price

        columns:
          - name: date
            description: The date when the product price was recorded
            data_type: date
            tests:
              - not_null
          - name: dedup_id
            description: Unique identifier for deduplication
            data_type: integer
            tests:
              - not_null
          - name: name
            description: The name of the product
            data_type: string
            tests:
              - not_null
          - name: size
            description: The size of the product
            data_type: string
            tests:
              - not_null
          - name: category
            description: The category of the product
            data_type: string
          - name: subcategory
            description: The subcategory of the product
            data_type: string
          - name: image_url
            description: URL of the product image
            data_type: string
          - name: price
            description: The final price of the product on the given date, discounted if exist otherwise the original price
            data_type: float
            tests:
              - not_null
              - dbt_utils.expression_is_true:
                  expression: "> 0"
          - name: price_ma_7
            description: 7-day moving average of the product price
            data_type: float
          - name: price_ma_15
            description: 15-day moving average of the product price
            data_type: float
          - name: price_ma_30
            description: 30-day moving average of the product price
            data_type: float
          - name: original_price
            description: The original price of the product before any discounts
            data_type: float
          - name: discount_price
            description: The price of the product after applying discounts
            data_type: float

      - name: incremental_merc
        description: Merc historical product prices

        config:
          freshness:
            warn_after: { count: 1, period: day }
            error_after: { count: 2, period: day }
          loaded_at_field: date

        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - date
                - dedup_id
                - name
                - size
                - category
                - subcategory
                - original_price
                - discount_price

        columns:
          - name: date
            description: The date when the product price was recorded
            data_type: date
            tests:
              - not_null
          - name: dedup_id
            description: Unique identifier for deduplication
            data_type: integer
            tests:
              - not_null
          - name: name
            description: The name of the product
            data_type: string
            tests:
              - not_null
          - name: size
            description: The size of the product
            data_type: string
            tests:
              - not_null
          - name: category
            description: The category of the product
            data_type: string
          - name: subcategory
            description: The subcategory of the product
            data_type: string
          - name: image_url
            description: URL of the product image
            data_type: string
          - name: price
            description: The final price of the product on the given date, discounted if exist otherwise the original price
            data_type: float
            tests:
              - not_null
              - dbt_utils.expression_is_true:
                  expression: "> 0"
          - name: original_price
            description: The original price of the product before any discounts
            data_type: float
            tests:
              - not_null
              - dbt_utils.expression_is_true:
                  expression: "> 0"
          - name: discount_price
            description: The price of the product after applying discounts
            data_type: float
