main:
  steps:
    - run-selenium-ingestor:
        call: googleapis.run.v1.executions.run
        args:
          name: projects/${sys.get_env("GCP_PROJECT_ID")}/locations/${sys.get_env("GCP_REGION")}/jobs/selenium-ingestor-job

    - create-dataproc-cluster:
        call: googleapis.dataproc.v1.clusters.create
        args:
          projectId: ${sys.get_env("GCP_PROJECT_ID")}
          region: ${sys.get_env("GCP_REGION")}
          cluster:
            clusterName: ephemeral-cluster
            config:
              masterConfig:
                machineTypeUri: n1-standard-2
              workerConfig:
                numInstances: 2
                machineTypeUri: n1-standard-2
        result: cluster_operation

    - initialize-cluster-wait-loop:
        assign:
          - cluster_done: false

    - wait-for-cluster:
        call: googleapis.dataproc.v1.operations.get
        args:
          name: ${cluster_operation.name}
        result: cluster_status

    - check-cluster-status:
        switch:
          - condition: ${cluster_status.done == true}
            assign:
              - cluster_done: true
          - condition: ${cluster_status.done == false}
            sleep:
              seconds: 10

    - repeat-wait-for-cluster:
        switch:
          - condition: ${cluster_done == false}
            next: wait-for-cluster

    - run-pyspark-job:
        call: googleapis.dataproc.v1.jobs.submit
        args:
          projectId: ${sys.get_env("GCP_PROJECT_ID")}
          region: ${sys.get_env("GCP_REGION")}
          job:
            placement:
              clusterName: ephemeral-cluster
            pysparkJob:
              mainPythonFileUri: gs://infass/pyspark-jobs/build_merc_table.py
        result: pyspark_job

    - initialize-job-wait-loop:
        assign:
          - job_done: false

    - wait-for-job:
        call: googleapis.dataproc.v1.operations.get
        args:
          name: ${pyspark_job.name}
        result: job_status

    - check-job-status:
        switch:
          - condition: ${job_status.done == true}
            assign:
              - job_done: true
          - condition: ${job_status.done == false}
            sleep:
              seconds: 10

    - repeat-wait-for-job:
        switch:
          - condition: ${job_done == false}
            next: wait-for-job

    - delete-dataproc-cluster:
        call: googleapis.dataproc.v1.clusters.delete
        args:
          projectId: ${sys.get_env("GCP_PROJECT_ID")}
          region: ${sys.get_env("GCP_REGION")}
          clusterName: ephemeral-cluster
