version: 2

models:
  - name: dbt_ref_product_price_details
    description: "Product details history in the Merc database"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date
            - id
    columns:
      - name: date
        description: "The date when the price was recorded"
        data_type: date
        tests:
          - not_null
      - name: id
        description: "The unique identifier for the product"
        data_type: string
        tests:
          - not_null
      - name: price
        description: "The price of the product"
        data_type: number
        tests:
          - not_null
      - name: sma7
        description: "The 7-day simple moving average of the product price"
        data_type: number
      - name: sma15
        description: "The 15-day simple moving average of the product price"
        data_type: number
      - name: sma30
        description: "The 30-day simple moving average of the product price"
        data_type: number
