FROM python:3.9-slim
WORKDIR /app
ENV PYTHONPATH=/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir pytest pytest

COPY ./app/ ./
COPY ./tests/ ./tests/

ENTRYPOINT ["pytest", "--disable-warnings"]