FROM python:3.9-slim AS python-build
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev \
    && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN python -m pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir pytest==8.4.0


FROM python:3.9-slim AS final
RUN apt-get update && apt-get install -y --no-install-recommends \
    chromium-driver chromium \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ENV PATH="/usr/lib/chromium/:$PATH" \
    PYTHONPATH=/app
VOLUME /dev/shm

COPY --from=python-build /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
COPY --from=python-build /usr/local/bin /usr/local/bin

WORKDIR /app
COPY ./app/ ./
COPY ./tests/ ./tests/
ENTRYPOINT ["pytest", "--durations=5", "-vv", "/app/tests/"]
