name: 'Trigger Cloud Run Job'
description: 'Authenticate to GCP and trigger a Cloud Run job with custom args.'

inputs:
  credentials_json:
    description: 'GCP credentials JSON secret.'
    required: true
  region:
    description: 'GCP region.'
    required: true
  app_name:
    description: 'App name.'
    required: true
  component:
    description: 'Component name.'
    required: true
  args:
    description: 'Arguments for the Cloud Run job.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2.1.12
      with:
        credentials_json: ${{ inputs.credentials_json }}

    - name: Trigger Cloud Run Job
      shell: bash
      run: |
        gcloud run jobs execute ${{ inputs.app_name }}-${{ inputs.component }} \
          --region ${{ inputs.region }} \
          --wait \
          --container=${{ inputs.component }} \
          --args="${{ inputs.args }}"
