infass:
  target: dev
  outputs:
    local:
      type: duckdb
      path: "inflation-assistant.duckdb"
      schema: infass

    dev:
      dataset: test_infass
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: infass-dbt-sa-cred-key.json
      location: EU
      method: service-account
      priority: interactive
      project: inflation-assistant
      threads: 1
      type: bigquery

    test:
      dataset: test_infass
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: EU
      method: service-account
      priority: interactive
      project: inflation-assistant
      threads: 1
      type: bigquery

    prod:
      dataset: infass
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: EU
      method: service-account
      priority: interactive
      project: inflation-assistant
      threads: 1
      type: bigquery
