version: 2

models:
  - name: dbt_dim_date
    description: "Calendar dimension at day grain with ISO week (Mon–Sun)."
    columns:
      - name: date
        description: "Calendar date (UTC-naive)."
        tests:
          - not_null
          - unique

      - name: date_key
        description: "YYYYMMDD integer surrogate for date."
        tests:
          - not_null
          - unique

      - name: year
        description: "Calendar year (e.g., 2025)."
        tests:
          - not_null

      - name: quarter
        description: "Calendar quarter (1–4)."
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "between 1 and 4"

      - name: month
        description: "Calendar month number (1–12)."
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "between 1 and 12"

      - name: month_key
        description: "YYYYMM integer (e.g., 202501)."
        tests:
          - not_null

      - name: month_name
        description: "Month name in locale (e.g., 'January')."
        tests:
          - not_null

      - name: iso_year
        description: "ISO week-numbering year."
        tests:
          - not_null

      - name: iso_week
        description: "ISO week number (1–53)."
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "between 1 and 53"

      - name: week_start_date
        description: "Start of ISO week (Monday)."
        tests:
          - not_null

      - name: week_end_date
        description: "End of ISO week (Sunday)."
        tests:
          - not_null

      - name: iso_week_key
        description: "ISO year+week key (e.g., 202501 or string '2025-01')."
        tests:
          - not_null

      - name: day_of_week
        description: "ISO day-of-week (1=Mon … 7=Sun)."
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "between 1 and 7"

      - name: day_of_month
        description: "Day of month (1–31)."
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "between 1 and 31"

      - name: day_of_year
        description: "Day of year (1–366)."
        tests:
          - not_null

      - name: is_weekend
        description: "True if Saturday or Sunday."
        tests:
          - not_null
          - accepted_values:
              values: [ true, false ]
              quote: false

      - name: month_start_date
        description: "First day of the month."
        tests:
          - not_null

      - name: month_end_date
        description: "Last day of the month."
        tests:
          - not_null

      - name: quarter_start_date
        description: "First day of the quarter."
        tests:
          - not_null

      - name: quarter_end_date
        description: "Last day of the quarter."
        tests:
          - not_null

      - name: year_start_date
        description: "First day of the year."
        tests:
          - not_null

      - name: year_end_date
        description: "Last day of the year."
        tests:
          - not_null

  - name: dbt_dim_product
    description: "Product dimension table."
    columns:
      - name: product_key
        description: "Surrogate key (hash of product_nk)."
        data_type: string
        tests:
          - not_null
          - unique

      - name: product_nk
        description: "Stable natural key: name + size."
        data_type: string
        tests:
          - not_null
          - unique

      - name: name
        description: "Product name."
        data_type: string
        tests:
          - not_null

      - name: size
        description: "Product size."
        data_type: string
        tests:
          - not_null

      - name: image_url
        description: "Latest observed image URL (Type-1)."
        tests:
          - dbt_utils.expression_is_true:
              expression: "is null or regexp_contains(image_url, r'^https?://')"

      - name: first_seen_date
        description: "First date the product_nk was observed."
        data_type: date
        tests:
          - not_null

      - name: last_seen_date
        description: "Most recent date the product_nk was observed."
        data_type: date
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= first_seen_date"
