name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
    paths:
      - '**'  # Trigger when any file is modified

env:
  GCS_BUCKET_URI: gs://infass
  GCP_REGION: europe-southwest1

jobs:
  test:
    name: Parallel Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [selenium-ingestor, spark-jobs, pandas-transformer]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Run Tests
        run: |
          cd ${{ matrix.service }}/
          docker buildx build --load -f Dockerfile.test -t test-image .
          docker run --rm test-image
  
  build-and-push:
    name: Parallel Build and Push
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        service: [selenium-ingestor, pandas-transformer]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Log in to Docker Registry
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          cd ${{ matrix.service }}/
          docker buildx build --load -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${GITHUB_SHA::7} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${GITHUB_SHA::7}
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${GITHUB_SHA::7} ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
  
  deploy-ingestor:
    name: Deploy Cloud Run Job
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.7
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy Cloud Run Job
        run: |
          gcloud run jobs update selenium-ingestor-job \
            --image ${{ secrets.DOCKER_USERNAME }}/selenium-ingestor:${GITHUB_SHA::7} \
            --service-account ${{ secrets.GCP_COMPUTE_SA }} \
            --region ${{ env.GCP_REGION }} \
            --max-retries 1 \
            --cpu 1 --memory 2Gi \
            --task-timeout 1200s

  deploy-pyspark-script:
    name: Deploy PySpark Script to GCS
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.7
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Upload PySpark Script
        run: |
          gcloud storage cp spark-jobs/spark_jobs/*.py ${{ env.GCS_BUCKET_URI }}/spark-jobs/

  deploy-workflow:
    name: Deploy Google Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.7
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy Workflow
        run: |
          gcloud workflows deploy merc-workflow --source workflow.yaml \
            --service-account ${{ secrets.GCP_COMPUTE_SA }} \
            --location ${{ env.GCP_REGION }} \
            --set-env-vars GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},GCP_REGION=${{ env.GCP_REGION }} \
            --verbosity=debug 

  terraform-deploy:
    name: Deploy infra using terraform
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      TF_VAR_APP_NAME: infass
      TF_VAR_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_REGION: europe-southwest1
      TF_VAR_DOCKER_HUB_USERNAME: gerardovitale
      TF_VAR_GCP_USER: ${{ secrets.GCP_USER }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2.1.3
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Terraform
        id: setup-tf
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: 1.10.4

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: false

      - name: Initialize Terraform
        id: init
        working-directory: ./tf-infra
        run: terraform init

      - name: Plan Terraform changes
        id: plan
        working-directory: ./tf-infra
        run: terraform plan -var "DOCKER_IMAGE_TAG=${GITHUB_SHA::7}"

      - name: Apply Terraform changes
        id: apply
        working-directory: ./tf-infra
        run: terraform apply -auto-approve -var "DOCKER_IMAGE_TAG=${GITHUB_SHA::7}"
