name: Trigger Transformer

on:
  schedule:
    - cron: "0 9 * * 6"

env:
  GCP_RUN_JOB_NAME: infass-pandas-transformer-job
  GCP_REGION: europe-southwest1

jobs:
  trigger-transformer:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.7
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Trigger Ingestor Cloud Run Job
        run: gcloud run jobs execute ${{ env.GCP_RUN_JOB_NAME }} --region ${{ env.GCP_REGION }}
