name: Trigger Transformer V2

on:
  schedule:
    - cron: "0 6 * * 6"
  workflow_dispatch:

jobs:
  trigger-transformer-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Trigger Cloud Run Job
        uses: ./.github/actions/trigger-cloud-run-job
        with:
          credentials_json: ${{ secrets.GCP_CICD_CREDENTIALS }}
          region: europe-southwest1
          app_name: infass
          component: transformer-v2
          args: "--gcs-source-bucket,test-bucket,--product,merc,--bq-destination-table,test-table"
