name: Trigger Ingestor

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

env:
  APP_NAME: infass
  GCP_REGION: europe-southwest1

jobs:
  trigger-ingestor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Trigger Ingestion Job
        id: trigger-ingestor
        uses: ./.github/actions/trigger-cloud-run-job
        with:
          credentials_json: ${{ secrets.GCP_CICD_CREDENTIALS }}
          region: ${{ env.GCP_REGION }}
          app_name: ${{ env.APP_NAME }}
          component: ingestor
          args: "https://tienda.mercadona.es,gs://infass-merc/merc"

      - name: Trigger Transformation Job
        id: trigger-transformer
        uses: ./.github/actions/trigger-cloud-run-job
        with:
          credentials_json: ${{ secrets.GCP_CICD_CREDENTIALS }}
          region: ${{ env.GCP_REGION }}
          app_name: ${{ env.APP_NAME }}
          component: transformer-v2
          args: "--gcs-source-bucket,infass-merc,--product,merc,--bq-destination-table,inflation-assistant.infass.incremental_merc"
