name: Trigger dbt transformations

on:
  schedule:
    - cron: "0 8 * * 6"
  workflow_dispatch:

jobs:
  trigger-dbt:
    uses: ./.github/workflows/dbt-workflow.yml
    with:
      dbt_profile: infass
      dbt_target: prod
      dbt_subcommand: build
      dbt_args: "" # e.g. "--select tag:nightly"
    secrets:
      gcp_credentials: ${{ secrets.GCP_DBT_CREDENTIALS }}

  trigger-reversed-etl:
    runs-on: ubuntu-latest
    needs: trigger-dbt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Trigger Transformation Job
        id: trigger-reversed-etl
        uses: ./.github/actions/trigger-cloud-run-job
        with:
          credentials_json: ${{ secrets.GCP_CICD_CREDENTIALS }}
          region: europe-southwest1
          app_name: infass
          component: reversed-etl-job
